[package]
name = "skia-test"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.12"
skia-safe = { version = "0.90.0", features = ["gl"] }
pollster = "0.4.0"
glutin = "0.32.3"
glutin-winit = "0.5.0"
gl = "0.14.0"
